openapi: 3.0.3
info:
    title: TODO API
    version: 1.0.0
    description: API de gestion de tâches.
servers:
    -   url: http://localhost:8080
        description: Serveur local

tags:
    -   name: tasks
        description: Gestion des tâches

paths:
    /tasks:
        post:
            tags: [ tasks ]
            summary: Créer une tâche
            operationId: createTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskCreateDto'
            responses:
                '201':
                    description: Succès
                    headers:
                        Location:
                            schema:
                                type: string
                                example: /tasks/1
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskResponseDto'
                '400':
                    description: Invalide
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ValidationErrorDto'

        get:
            tags: [ tasks ]
            summary: Liste des tâches
            operationId: getAllTasks
            parameters:
                -   in: query
                    name: todo-only
                    required: false
                    schema:
                        type: boolean
            responses:
                '200':
                    description: Succès
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/TaskResponseDto'
                '204':
                    description: Aucun résultat

    /tasks/{id}:
        parameters:
            -   in: path
                name: id
                required: true
                schema:
                    type: integer
                    minimum: 1
        get:
            tags: [ tasks ]
            summary: Voir une tâche
            operationId: getTaskById
            responses:
                '200':
                    description: Succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskResponseDto'
                '404':
                    description: Introuvable

        delete:
            tags: [ tasks ]
            summary: Supprimer une tâche
            operationId: deleteTask
            responses:
                '204':
                    description: Succès
                '404':
                    description: Introuvable

        put:
            tags: [ tasks ]
            summary: Modifier une tâche
            operationId: updateTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskUpdateDto'
            responses:
                '204':
                    description: Succès
                '400':
                    description: Invalide
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ValidationErrorDto'
                '404':
                    description: Introuvable
components:
    schemas:
        TaskCreateDto:
            type: object
            required:
                - title
            properties:
                title:
                    type: string
                    maxLength: 50
                    example: Rendre le projet
                description:
                    type: string
                    maxLength: 255
                    example: Push le code sur le GitLab.

        TaskUpdateDto:
            type: object
            required:
                - title
                - done
            properties:
                title:
                    type: string
                    maxLength: 50
                    example: Réviser le DS
                description:
                    type: string
                    maxLength: 255
                    example: Relire le cours de maths.
                done:
                    type: boolean
                    example: true

        TaskResponseDto:
            type: object
            required:
                - id
                - title
                - done
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    maxLength: 50
                    example: Acheter les softs
                description:
                    type: string
                    maxLength: 255
                    example: Prendre des sodas pour la soirée.
                done:
                    type: boolean
                    example: false

        ValidationErrorDto:
            type: object
            properties:
                field:
                    type: string
                    example: title
                message:
                    type: string
                    example: Le titre ne doit pas dépasser 50 caractères.